'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8800
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Retailer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property arrowdownpng50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowdownpng50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowleftpng50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowleftpng50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowrightpng50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowrightpng50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowupng50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowupng50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancelmat50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelmat50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coinspng50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coinspng50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coinspng96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coinspng96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connectc24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connectc24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cubespng24() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cubespng24", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property cubespng48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cubespng48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cubespng96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cubespng96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property deleteticket_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deleteticket_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doorhanger_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doorhanger_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enterkey96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enterkey96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enterkeypng48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enterkeypng48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property goldbars24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goldbars24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property handpng50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("handpng50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property handpng60() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("handpng60", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property importc24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("importc24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property insertcard_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("insertcard_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoicediscountpng100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoicediscountpng100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property linediscount96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("linediscount96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property microsoftexcel96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("microsoftexcel96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property moremat50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moremat50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nextmat50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nextmat50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property othersettlepng48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("othersettlepng48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pausepng96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pausepng96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pricetag96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pricetag96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pricetagc24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pricetagc24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property savefilled_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savefilled_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property savepng50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savepng50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stackpng50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stackpng50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unavailablefilled_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unavailablefilled_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undopng60() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undopng60", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usergroups24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usergroups24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
